/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "IoT": {
      "Endpoint": string
      "type": "sst.sst.Linkable"
    }
    "IoTAPI": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
